version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
#      nodejs: 12.x
    commands:
      - apt-get update
      - apt-get install -y wget unzip curl gnupg

      - curl -sSL https://dl.google.com/linux/linux_signing_key.pub | apt-key add -

      - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list

      - apt-get update
      - apt-get install -y google-chrome-stable

      - pip install -r requirements.txt  # Instalar dependências Python
#      - npm install  # Instalar dependências Node.js, se necessário
  pre_build:
    commands:
      - echo Iniciando testes...
  build:
    commands:
      - behave --no-capture -f allure -o logs ./features
  post_build:
    commands:
      - echo Testes concluídos
#      - aws s3 cp reports/ s3://meu-bucket-de-relatorios/ --recursive  # Enviar relatórios de teste para o S3
#artifacts:
#  files:
#    - '**/*'
#  base-directory: 'reports'
#  discard-paths: yes
