version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
#      nodejs: 12.x
    commands:
      - pip install -r requirements.txt  # Instalar dependências Python
#      - npm install  # Instalar dependências Node.js, se necessário
  pre_build:
    commands:
      - echo Iniciando testes...
  build:
    commands:
      - behave --no-capture -f allure -o logs ./features
  post_build:
    commands:
      - echo Testes concluídos
#      - aws s3 cp reports/ s3://meu-bucket-de-relatorios/ --recursive  # Enviar relatórios de teste para o S3
artifacts:
  files:
    - '**/*'
  base-directory: 'reports'
  discard-paths: yes
